### ISSUE TITLE
Desenvolver um painel de controle web [Frontend]

### ISSUE THREAD

**Issue by aureliowozhiak** [aureliowozhiak/DLaaS#12]
Desenvolver do zero um painel de controle web para gerenciar o Data Lake. Isso facilitará o gerenciamento de fontes de dados, configurações e monitoramento.

**Comment by lgcavalheiro** [comment]
Talvez seja meio cedo pra ver isso, mas tenho algumas sugestoes dependendo do approach que vcs quiserem fazer:

## Monolitico
Com svelte da pra gente servir um frontend SPA do python mesmo com Flask ou outro framework, ex: 

- https://cabreraalex.medium.com/svelte-js-flask-combining-svelte-with-a-simple-backend-server-d1bc46190ab9
- https://github.com/lgcavalheiro/go-svelte-embed-starter (mesmo principio feito em Go)

Ou usar o inertia.js, mas so tem adapter pro Django: https://github.com/inertiajs/inertia-django

Ou usar um framework python puro e deixar tudo no server side (Django puro, por exemplo)

## Sem ser monolitico
Ai e criar um repo novo so pro front, e ele vai ter que ser deployado separado do DLaaS, mas vamos ter mais liberdade pra usar outros frameworks js

**Comment by Felipe-Tomazetti** [comment]
@lgcavalheiro Eu trabalho com ReactJS e entrei no projeto para poder auxiliar com a parte da interface. Você está no discord para trocarmos uma ideia?

**Comment by lgcavalheiro** [comment]
@Felipe-Tomazetti to no discord como kensh9000, só chamar lá!

**Comment by salles95** [comment]
Boa noite pessoal,

Se eu puder contribuir em algo nesta issue, eu estou estudando React aqui para aplicar front end em aplicações de dados.
@lgcavalheiro @Felipe-Tomazetti
