### ISSUE TITLE
Criar esteira de integração continua (CI)

### ISSUE THREAD

**Issue by aureliowozhiak** [aureliowozhiak/DLaaS#17]
esteira de CI para rodar os testes automatizados, podemos usar o GitHub Actions..o ideal seria a esteira rodar sempre que houver um PR para master

**Comment by aureliowozhiak** [comment]
@razevedo1994 falta algo pra fechar essa issue?

**Comment by razevedo1994** [comment]
Falta nao, vou fechar!
