### ISSUE TITLE
Por o projeto em um dockerfile

### ISSUE THREAD

**Issue by aureliowozhiak** [aureliowozhiak/DLaaS#20]
Criar um dockerfile pra normalizar versão do python e dependências

**Comment by devbrunorm** [comment]
Posso atual nessa frente, se quiser

**Comment by aureliowozhiak** [comment]
@devbrunorm pode ser, obrigado!

**Comment by devbrunorm** [comment]
@aureliowozhiak, se puder, me mande um pessoal que possa revisar o PR também além de você. Acho que esse PR é meio crítico

**Comment by aureliowozhiak** [comment]
vcs podem dar uma mão? @lgcavalheiro e @eduwxyz ?

**Comment by lgcavalheiro** [comment]
Aparentemente é erro de path de import, vou revisar aqui e retorno
