### ISSUE TITLE
Criar documentação em inglês do projeto

### ISSUE THREAD

**Issue by Priscaruso** [aureliowozhiak/DLaaS#28]
- Criar um README.md em inglês para que pessoas do mundo todo tenham acesso ao projeto

**Comment by aureliowozhiak** [comment]
Acho valido deixar o README.md direto em ingles, e fazer uma versão secundária em portugues (mover a atual para um README.pt.md por exemplo e só "Linkar" no topo do oficial.

**Comment by Priscaruso** [comment]
É uma boa mesmo @aureliowozhiak. Vou fazer isso.

**Comment by aureliowozhiak** [comment]
@Priscaruso se precisar de ajuda durante a semana é só me avisar.
