### ISSUE TITLE
Criar suporte para paginação de requisições de APIs

### ISSUE THREAD

**Issue by aureliowozhiak** [aureliowozhiak/DLaaS#3]
Na classe de conexão com APIs (apiRequests.py) criar esse suporte para diferentes tipos de paginação possíveis e parâmetros de consulta.

Ex.:
"pagination_method":
{
                "limit_text": "limite",
                "limit_value": 100,
                "page_text": "i",
                "page_start": 1,
                "page_step":10
            }

**Comment by aureliowozhiak** [comment]
@razevedo1994 vi que vc assinou o card, já tem alguma noção de como começar? se precisar de ajuda pode chamar ai

**Comment by razevedo1994** [comment]
@aureliowozhiak Pensando no desenvolvimento, acho que nesse primeiro momento o melhor seria um método de paginação para o cenário da API que temos, e a adequação da classe para que ela fique fácil de ser estendida e o suporte para outros métodos de paginação facilmente acoplados. Penso que abstrair todos as formas de paginação nesse momento possa ser um over engineering. Faz sentido?

**Comment by aureliowozhiak** [comment]
@razevedo1994  Ah, sim. Concordo com seu ponto.

O que podemos fazer é, criar a paginação pra alguma fonte, mas deixar ela genérica e modular, para conseguir ir evoluindo isso sem precisar redatora muito o código no decorrer do desenvolvimento.

Mas sim, podemos fazer algo que funcione pra uma fonte e ir melhorando com o tempo.

**Comment by razevedo1994** [comment]
Maravilha então! Tem alguma API em mente para essa primeira implementação, conseguiria me passar a doc?

**Comment by aureliowozhiak** [comment]
@razevedo1994 
Pode usar essa como base:

https://api.github.com/repositories/1300192/issues?page=2

acho que é a mais básica, ir iterando o valor de "page"
