### ISSUE TITLE
Padronização dos comentários dos códigos

### ISSUE THREAD

**Issue by Priscaruso** [aureliowozhiak/DLaaS#36]
Conforme discutido no PR #35, utilizaremos o inglês como padrão para os comentários dos códigos a partir de agora. Então, precisamos consertar os códigos prontos que estão com comentários em português e os que estão sem comentários também.

**Comment by eduwxyz** [comment]
Tem bastantes classe/função que não tem nenhuma documentação sobre qual o objetivo dela. Seria legal já utilizarmos o padrão de [docstring](https://www.programiz.com/python-programming/docstrings). Acho que todas as mudanças/adições não precisam estar em um único PR pq já tem bastante código e seria bastante trabalhoso, mas dá pra ir adicionando isso aos poucos.

**Comment by Priscaruso** [comment]
> Tem bastantes classe/função que não tem nenhuma documentação sobre qual o objetivo dela. Seria legal já utilizarmos o padrão de [docstring](https://www.programiz.com/python-programming/docstrings). Acho que todas as mudanças/adições não precisam estar em um único PR pq já tem bastante código e seria bastante trabalhoso, mas dá pra ir adicionando isso aos poucos.

Verdade. É uma boa ir fazendo aos poucos mesmo, até para não gerar conflitos de código também. Acho que a galera que fez o seu próprio código poderia documentar isso depois porque aí fica melhor até de explicar o que foi feito também.
