### ISSUE TITLE
Create new funcionality for WebDataScrapper

### ISSUE THREAD

**Issue by Priscaruso** [aureliowozhiak/DLaaS#38]
This issue will add a new funcionality for the WebDataScrapper extractor which will execute the following:
- Get the html links of all pages

**Comment by Priscaruso** [comment]
I did a modification of the first intended functionality because the majority of pages are SPA now. Instead of getting all pages link, it gets all the internal links from the page. Using these links as arguments for the class WebPageDataScrappers, we can navigate through all of them.

**Comment by aureliowozhiak** [comment]
It's all done? Can we close this issue @Priscaruso ?

**Comment by Priscaruso** [comment]
@aureliowozhiak I was thinking about trying a recursion method, but I don't know if it will work as we are making generic methods.  We can close for now.

**Comment by aureliowozhiak** [comment]
Okay, so we can create a new issue for this recursion method. @Priscaruso
