### ISSUE TITLE
Criar classes para conectores com bancos de dados

### ISSUE THREAD

**Issue by aureliowozhiak** [aureliowozhiak/DLaaS#4]
Criar super classe de conectores para extrair dados de bancos de dados, mas também criar as classes especificas, quando necessário para atender as peculiaridades (polimorfismo) de cada banco.

Primeiros bancos para desenvolver:
- [x] MySQL
- [x] PostgreSQL
- [x] SQLite

**Comment by aureliowozhiak** [comment]
Seria interessante criar um conector para o banco da Oracle

**Comment by devbrunorm** [comment]
Posso ver de criar uma classe para o MySQL

**Comment by aureliowozhiak** [comment]
> Posso ver de criar uma classe para o MySQL

Boa, vai avisando se precisar de algo.

**Comment by RVegh** [comment]
To trabalhando na criação da do Postgres por enquanto, amanhã devo subir aqui pra revisarem. Pra agora será uma classe pra cada um desses bancos mesmo ?

**Comment by aureliowozhiak** [comment]
@RVegh isso, a ideia é ter uma classe pra cada, como um conector + executor de query (select), quando a gente tiver duas classes prontas a gente vai conseguir pensar em criar uma classe "pai" pra generalizar o que for igual.

**Comment by devbrunorm** [comment]
Pessoal, estive pensando esses dias e acho que para criar esses conectores seria legal usarmos o sqlalchemy. É uma lib que tem vários conectores de banco embutidos. Acho que isso simplificaria as coisas e evitaria de ficar fazendo muitos imports diferentes. O que acham?

**Comment by aureliowozhiak** [comment]
é uma boa @devbrunorm, adiciona pra gente no requirements.txt?

**Comment by devbrunorm** [comment]
Crio, sim. Assim que puder, eu coloco ela.

**Comment by RVegh** [comment]
> Pessoal, estive pensando esses dias e acho que para criar esses conectores seria legal usarmos o sqlalchemy. É uma lib que tem vários conectores de banco embutidos. Acho que isso simplificaria as coisas e evitaria de ficar fazendo muitos imports diferentes. O que acham?

Eu estava criando usando o psycopg2, mas posso alterar se quiserem

**Comment by aureliowozhiak** [comment]
> > Pessoal, estive pensando esses dias e acho que para criar esses conectores seria legal usarmos o sqlalchemy. É uma lib que tem vários conectores de banco embutidos. Acho que isso simplificaria as coisas e evitaria de ficar fazendo muitos imports diferentes. O que acham?
> 
> Eu estava criando usando o psycopg2, mas posso alterar se quiserem

Seria bom normalizar em uma só, vamos usar a sugestão do Bruno, mas se quiser, deixa o código que vc fez comentado, para não perder seu trabalho tbm.

**Comment by devbrunorm** [comment]
Pior que eu também tinha começado em uma lib própria de MySQL. Depois que eu tive a ideia. Mas acho que é bom trocarmos agora que estamos no começo para evitar retrabalho no futuro

**Comment by aureliowozhiak** [comment]
claro, é bom a gente deixar essa base mais redonda possível mesmo.

**Comment by aureliowozhiak** [comment]
@devbrunorm acho que vc fechou a issue junto com o Merge

**Comment by devbrunorm** [comment]
Hmmm, talvez a issue estava vinculada a aquela branch

**Comment by aureliowozhiak** [comment]
Como falei no discord, vamos refatorar essa classe, pra tentar aumentar a manutentabilidade dela
