### ISSUE TITLE
Iniciar a implementação de testes no desenvolvimento do projeto

### ISSUE THREAD

**Issue by aureliowozhiak** [aureliowozhiak/DLaaS#5]
Aprender mais sobre testes e como implementar no projeto;
Ir atrás de pessoas que entendam de testes para ajudar no projeto ou até mesmo ensinar;
E entender qual nível de teste seria interessante colocar no projeto (unitários, integração, de sistema, ou outro tipo);

+ E em paralelo, entender como os "testes" podem ajudar no futuro com qualidade de dados.

**Comment by aureliowozhiak** [comment]
pesquisar mais sobre o software "great expectations" e alternativas

**Comment by lgcavalheiro** [comment]
A gente ta dando preferência pra alguma lib de teste em específico? To usando o unittest com coverage só, mas vi em um pr o uso do pytest: https://github.com/aureliowozhiak/DLaaS/pull/26

Qual iremos usar?

**Comment by aureliowozhiak** [comment]
Pode ser pytest mesmo, se você tiver familiaridade com ele.

**Comment by lgcavalheiro** [comment]
Resolvido em https://github.com/aureliowozhiak/DLaaS/pull/30, caso não tenhamos mais nada para resolver relativo a essa issue, podemos fechar.

**Comment by aureliowozhiak** [comment]
acredito que é isso mesmo, vou fechar a issue, pq a ideia era começar os testes mesmo, obrigado @lgcavalheiro
